"""
Django settings for elektronika project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n!4*p49gd8t3cvr@ugr=7tb8pskuskrnyvej3_!z+23@!ibb$h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pokaz_elektroniki',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'elektronika.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'elektronika.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import os

# Use persistent disk on Render, or local db for development
if os.environ.get('RENDER'):
    # Render sets RENDER=true. Try to use the persistent disk at /data
    try:
        os.makedirs('/data', exist_ok=True)
        DB_PATH = str(Path('/data/db.sqlite3'))
    except PermissionError:
        # If we can't create or write to /data, fall back to the local DB
        DB_PATH = str(BASE_DIR / 'db.sqlite3')
else:
    DB_PATH = str(BASE_DIR / 'db.sqlite3')

# Debug: Print database location to help diagnose issues
print(f"\n{'='*60}", file=__import__('sys').stderr)
print(f"DJANGO SETTINGS LOADED", file=__import__('sys').stderr)
print(f"RENDER env var: {os.environ.get('RENDER', 'NOT SET')}", file=__import__('sys').stderr)
print(f"Database path: {DB_PATH}", file=__import__('sys').stderr)
print(f"Database exists: {os.path.exists(DB_PATH)}", file=__import__('sys').stderr)
print(f"{'='*60}\n", file=__import__('sys').stderr)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DB_PATH,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'pl'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploads)
# Store on persistent disk if on Render, otherwise local for development
if os.environ.get('RENDER'):
    MEDIA_ROOT = Path('/data/zdjęcia')
else:
    MEDIA_ROOT = BASE_DIR / 'zdjęcia'
# MEDIA_URL should start and end with a slash so URLs resolve correctly
MEDIA_URL = '/zdjęcia/'

# Static files (for production)
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Only include STATICFILES_DIRS if the directory exists
if os.path.exists(BASE_DIR / 'static'):
    STATICFILES_DIRS = [BASE_DIR / 'static']
else:
    STATICFILES_DIRS = []
# Use WhiteNoise to serve static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
