# Generated by Django 5.1.5 on 2026-02-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Część_elektroniczna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('opis', models.TextField()),
                ('zdjęcie', models.ImageField(upload_to='zdjęcia')),
            ],
            options={
                'verbose_name': 'Część elektroniczna',
                'verbose_name_plural': 'Części elektroniczne',
            },
        ),
    ]
